// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	GetPatient(ctx context.Context, id int64) (Patient, error)
	ListPatients(ctx context.Context) ([]Patient, error)
}

var _ Querier = (*Queries)(nil)
